# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:
- job: Job_1
  displayName: DEx Execution On Remote VMWare Machine
  pool:
    name: Default
  steps:
  - checkout: self
  - task: CmdLine@1
    displayName: Run TOSCA CI Client
    inputs:
      filename: $(Agent.HomeDirectory)\\_work\\tosca_ci\\Client\\ToscaCIClient.exe
      arguments: -m distributed -c $(Agent.HomeDirectory)\\CIExecution\CITestExecutionConfiguration.xml -t junit -r $(Agent.HomeDirectory)\\_work\\2\\TestResults\\ToscaCI.xml
  - task: PublishTestResults@2
    displayName: Publish Test Results Result.xml
    inputs:
      testResultsFiles: ToscaCI.xml
      searchFolder: $(Agent.HomeDirectory)\\_work\\2\\TestResults
